### ISSUE TITLE
Stack misalignment

### ISSUE THREAD

**Issue by XuhengLi** [Lenz-K/kvm-test#2]
Hi @Lenz-K,

Thank you for sharing your code. While your unmodified code works perfectly, I found that the stack setup in your linker script might be misaligned:
https://github.com/Lenz-K/arm64-kvm-hello-world/blob/be84bf7c5234ff9f23f68664623c1bd16e85fdca/bare-metal-aarch64-qemu/link_script.ld#L10

Based on Arm ABI(https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst#the-stack), the stack pointer should always be aligned to 16-byte(quad-word).

The current specific code works because the `stack_top` happens to be aligned to 16-byte but if some changes were made to the code or makefile, this could be broken.

This can be easily fixed by set alignment to 16.

Cheers!

**Comment by Lenz-K** [comment]
Hi @XuhengLi,
Thanks for the feedback. I fixed it here: 5b72de8b2877653f1875dc92cd379e9c63e8ed5a

Have a great day!
