### ISSUE TITLE
Page size problems - invalid argument on KVM_SET_USER_MEMORY_REGION 

### ISSUE THREAD

**Issue by Vbitz** [Lenz-K/kvm-test#4]
I was testing the code on my Raspberry PI 5 and it failed to set the user memory regions.

Looks like the kernel I'm running has 16k pages rather than the 4k standard size.

I got it working in another project by setting the region sizes to 16k.

**Comment by Lenz-K** [comment]
@Vbitz Thanks for letting me know. I will look into it.

**Comment by Lenz-K** [comment]
@Vbitz I tried to run the Raspberry Pi OS kernel which is used for the Raspberry Pi 5 with the page size of 16kB (`kernel_2712.img`) on my Raspberry Pi 4. This seems not to work. I also did not find any other kernel with 16kB page size.

Therefore I can not reproduce it for now. I do not intend to compile a modified kernel myself for now. I might come back to it when I get a Raspberry Pi 5.

I would also be happy to merge a fix if you have one.
